research_task:
  description: >
    Сформируй из этого задания корректный поисковый запрос в интернет: {search_query} 
    
    Используй свой сформированный запрос для поиска ответа в интернете.
    Сначала подумай над ответом на тестовое задание сам, а потом, используя поисковую выдачу для анализа, дай финальный ответ. 
    ПРАВИЛЬНО и ВДУМЧИВО отвечай на вопрос!
  expected_output: >
    СТРОГИЙ JSON ответ формата:
       "answer": str | null,  # Если вопрос требует выбора из предложенных вариантов (например, 1-10), укажи номер правильного ответа. Если вопрос открытый, ответ будет null.
       "reasoning": str,  # Подробное и логичное обоснование НА РУССКОМ ЯЗЫКЕ твоего ответа с интересными фактами. Ты должен объяснить, как пришел к выводу.
       "sources": list[str]  # Укажи ТРИ ссылки из поисковой выдачи, которые ты использовал для ответа. Примеры ссылок должны быть в формате: ["https://example.com", "https://another-example.com", "https://yetanother.com"].
    Должен быть СЫРОЙ JSON файл для сериализации и без всяких дополнительных знаков!